dataset_path: "src/data"
test_image: "src/test_image.jpg"

# Model settings
model_path: "src/models/face_recognition_model.h5"
encoder_path: "src/models/label_encoder.pkl"
input_shape: [160, 160, 3]

# Training parameters
batch_size: 32
epochs: 10
learning_rate: 0.001
optimizer: "adam"
loss_function: "triplet_loss"

# Data processing
image_size: [160, 160]
normalization: True
augmentation: True

# Output directories
results_path: "results/"
train_test_data_path: "results/faces_train_test.npz"  
deploy_data_path: "results/faces_deploy.npz"

# Logging settings
log_level: "INFO"
save_logs: True
log_file: "logs/pipeline.log"

